<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pdflister"
 *
 * Auto generated by Extension Builder 2015-11-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'PDF Lister',
	'description' => 'This extension lists PDF files from a selected Folder. The website users can download these PDF files securely, without knowing the actual PDF path. The extension also allows signing up such downloaded PDF files with a custom message.',
	'category' => 'plugin',
	'author' => 'Prakash A Bhat',
	'author_email' => 'info@scwebs.in',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.19',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);